
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmul_mec_matrix.h"

/*
* The configuration table for devices
*/

XMul_mec_matrix_Config XMul_mec_matrix_ConfigTable[XPAR_XMUL_MEC_MATRIX_NUM_INSTANCES] =
{
	{
		XPAR_MUL_MEC_MATRIX_0_DEVICE_ID,
		XPAR_MUL_MEC_MATRIX_0_S_AXI_CONTROL_BASEADDR
	}
};


